### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by LuminFX** [LuminFX/ActiveU#2]
User story: As a user, I should be able to easily view a page and log into my account

Acceptance Criteria: As the user, I should be able to view the Login page which includes a form for username and password, a hyperlink for the register page, and images/design that is pleasing to the eye

**Comment by SarthakPaithankar** [comment]
Finished Login/Logout page with pictures. Login has a form to enter username/password. Logout has a message confirming logout and has a form to enter username/password to log back in. Need to center the logout text. Also added the header and footers
